name: Bike Share Project Deployment

on:
  workflow_run:
    workflows: ["Bike Share project Docker build."]
    types:
      - completed
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Read VERSION file and set as environment variable
        run: |
         echo "VERSION=$(cat bikeshare_model/VERSION)" >> $GITHUB_ENV
       
      - name: Pull the  docker image which build on ci.ymal
        run: |
          sudo docker pull ${{ secrets.DOCKERHUB_UNAME }}/bike_sharing_api:$VERSION

      - name: Run bikesharing api image
        run: |
          sudo docker run -d -p 8001:8001 ${{ secrets.DOCKERHUB_UNAME }}/bike_sharing_api:$VERSION
          
  
      
